name: coffeeshop

services:
  backend:
    image: ${DH_USER}/coffeeshop-backend:latest
    container_name: coffeeshop-backend
    restart: unless-stopped
    ports:
      - "8099:8099"  # host:container
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffeeshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
      SERVER_PORT: "8099"
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m -XX:+UseSerialGC"

  frontend:
    image: ${DH_USER}/coffeeshop-frontend:latest
    container_name: coffeeshop-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # React sẽ gọi API qua container backend
      REACT_APP_API_URL: http://localhost:8099
